/* UI utilities (toast, theme, scroll reveal) adapted from ProTask Elite */
const UI = (function(){
  const createToastContainer = ()=>{ let c=document.getElementById('toast-container'); if(!c){ c=document.createElement('div'); c.id='toast-container'; c.className='toast-container'; document.body.appendChild(c);} return c; };
  const toast = (title,message='',type='info',duration=3500)=>{ const container = createToastContainer(); const icons={success:'✅',error:'❌',info:'ℹ️',warning:'⚠️'}; const el=document.createElement('div'); el.className=`toast ${type}`; el.innerHTML=`<div class="toast-icon">${icons[type]||icons.info}</div><div class="toast-body"><div class="toast-title">${title}</div>${message?`<div class="toast-msg">${message}</div>`:''}</div>`; container.appendChild(el); const remove=()=>{ el.classList.add('removing'); setTimeout(()=>el.remove(),300); }; el.addEventListener('click', remove); setTimeout(remove,duration); };
  const initTheme = ()=>{ const saved = localStorage.getItem('protask_theme')||'dark'; document.documentElement.setAttribute('data-theme', saved); updateThemeIcon(saved); return saved; };
  const toggleTheme = ()=>{ const current = document.documentElement.getAttribute('data-theme')||'dark'; const next = current==='dark' ? 'light' : 'dark'; document.documentElement.setAttribute('data-theme', next); localStorage.setItem('protask_theme', next); updateThemeIcon(next); return next; };
  const updateThemeIcon = (theme)=>{ document.querySelectorAll('.theme-icon').forEach(icon=>{ icon.textContent = theme==='dark' ? '☀️' : '🌙'; }); };
  const initScrollReveal = ()=>{ const items=document.querySelectorAll('.reveal'); if(!items.length) return; const observer = new IntersectionObserver((entries)=>{ entries.forEach(entry=>{ if(entry.isIntersecting){ entry.target.classList.add('visible'); observer.unobserve(entry.target); } }); },{ threshold: 0.12, rootMargin: '0px 0px -40px 0px' }); items.forEach(item=>observer.observe(item)); };
  const hideLoader = ()=>{ const loader=document.getElementById('page-loader'); if(loader) setTimeout(()=>loader.classList.add('hide'),400); };
  const animateCounter = (el,target,duration=1200)=>{ const start = parseInt(el.textContent)||0; const range = target-start; const startTime = performance.now(); const update = (now)=>{ const elapsed = now - startTime; const progress = Math.min(elapsed/duration,1); const eased = 1 - Math.pow(1-progress,3); el.textContent = Math.round(start + range*eased); if(progress<1) requestAnimationFrame(update); }; requestAnimationFrame(update); };
  const initSidebar = ()=>{ const toggle=document.getElementById('sidebar-toggle'); const sidebar=document.getElementById('sidebar'); const overlay=document.getElementById('sidebar-overlay'); if(!toggle||!sidebar) return; toggle.addEventListener('click', ()=>{ sidebar.classList.toggle('open'); overlay?.classList.toggle('show'); }); overlay?.addEventListener('click', ()=>{ sidebar.classList.remove('open'); overlay.classList.remove('show'); }); };
  return { toast, initTheme, toggleTheme, initScrollReveal, hideLoader, animateCounter, initSidebar };
})();
window.UI = UI;
